
@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjgyMjg1MzNhZjU5NzJhMzIxZTA4YTBiIiwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIn0sImlhdCI6MTc0NzEyMDQxMiwiZXhwIjoxNzQ3MTI0MDEyfQ.mhbZeNnuNJZZZgnR4gYD2UHtWpjact2-bXTBGbW1g-I

### User Sigup
POST {{host}}/api/auth/signup
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "password": "123456"
}


### User Sigin
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "email": "john@example.com",
    "password": "123456"
}


### Fetch ME
GET {{host}}/api/auth/me
Authorization: Bearer {{token}}
Content-Type: application/json


